---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install MySQL server and Python MySQL library
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - python3-mysqldb


- name: Configure MySQL bind address
  become: true
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: "bind-address = 0.0.0.0"
    state: present
    backup: yes
  notify: Restart MySQL
  
- name: Start the MySQL service
  action: service name=mysql state=started

- name: Set root user password
  become: true
  become_user: root
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy .my.cnf file with root password credentials
  become: true
  become_user: root
  template: src=roles/mysql/templates/.my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: Create mysql user
  become: true
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    host: "%"
    priv: "*.*:ALL"
    state: present
  notify: Restart MySQL

- name: Create mysql database
  become: true
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present

- name: Delete anonymous MySQL server user for $server_hostname
  become: true
  action: mysql_user user="" host="{{ server_hostname }}" state="absent"
  
- name: Delete anonymous MySQL server user for localhost
  become: true
  action: mysql_user user="" state="absent"

- name: Remove the MySQL test database
  become: true
  action: mysql_db db=test state=absent

- name: Update mysql root password for all root accounts
  become: true
  mysql_user: name=root host={{ server_hostname }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
  with_items:
    - "{{ ansible_hostname }}"
    - "{{wp_db_ip}}"
    - ::1
    - localhost
  notify: Restart MySQL